services:
  backend:
    build:
      context: ./backend
    container_name: bp-backend
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/app/src

  frontend:
    build:
      context: ./frontend
    container_name: bp-frontend
    environment:
      VITE_API_BASE_URL: /api
      VITE_BACKEND_URL: http://backend:3000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    depends_on:
      - backend
